arr:
  ema_decay: 0.999
  enabled: true
  n_arr: 1024
  net:
    depth: 4
    dropout: 0.0
    embed_dim: 512
    ff_factor: 4
    n_head: 8
    n_vf_cat: 3
    pos_emb_std: 0.1
    use_cat_vf: true
  ppo:
    autocast_dtype: float32
    batch_size: 256
    clip_range: 0.2
    ent_pred_coef: 0.5
    kl_coef: 0.1
    lr: 0.0003
    max_grad_norm: 0.5
    num_epoch_per_train: 4
    policy_coef: 1.0
    vf_coef: 0.5
    weight_decay: 0.0
  refresh_every: 1
  reg_norm: 10.0
  reg_temp_decay: 0.3
  reg_temp_floor: 0.0
  reg_temp_init: 0.1
  storage_duration: 4
device: cuda
env:
  max_num_moves: 4000
  num_envs: 128
  seed: 42
  steps_per_env: 512
  use_gpu_rollout: true
eval_every: 10
log_every: 5
net:
  action_key_dim: 32
  cnn_channels: 64
  cnn_layers: 2
  depth: 4
  dropout: 0.0
  embed_dim: 128
  ff_factor: 4
  n_head: 4
  pos_emb_std: 0.02
  use_cat_vf: true
ppo:
  adv_filt_rate: 0.6
  adv_filt_thresh: 0.005
  clip_range: 0.2
  dtype: float16
  ema_decay: 0.999
  gae_lambda: 0.5
  gamma: 1.0
  kl_coef: 0.1
  lr_ceil: 0.0001
  lr_coef: 0.5
  lr_decay: 1.1
  lr_floor: 5.0e-06
  max_grad_norm: 0.267
  minibatch_size: 512
  net:
    action_key_dim: 32
    cnn_channels: 64
    cnn_layers: 2
    depth: 4
    dropout: 0.0
    embed_dim: 128
    ff_factor: 4
    n_head: 4
    pos_emb_std: 0.02
    use_cat_vf: true
  num_epochs_per_rollout: 1
  policy_coef: 1.0
  td_lambda: 0.8
  temperature_ceil: 0.1
  temperature_coef: 0.05
  temperature_decay: 0.3
  temperature_floor: 0.001
  torch_compile: true
  uniform_magnet: true
  vf_coef: 1.0
  weight_decay: 0.0
resume: ''
save_dir: exps/beat_random_v18_buffer_fix
save_every: 50
seed: 42
torch_deterministic: false
total_rollouts: 500
use_wandb: false
wandb_project: junqi-rl
wandb_run_name: ''
