
"""Golden test scenario construction DSL (domain-specific language).

High-level API for writing golden JSON cases concisely, correctly, and
self-checked.  Example:

    from tests.golden._dsl import Case, SOUTH, NORTH, SILING, ZHADAN

    case = (
        Case("siling_attacks_zhadan_src_only_reveal", category="siling_flag")
        .describe("SOUTH SILING attacks NORTH ZHADAN; BOMB; only src reveals.")
        .tag("Q7", "siling", "zhadan")
        .turn(SOUTH)
        .place(SOUTH, index=3,  piece=SILING, at=(8, 10))
        .place(NORTH, index=11, piece=ZHADAN, at=(8, 5))
        .act(SOUTH, src=(8, 10), dst=(8, 5))
        .expect_result(event="BOMB", flag_reveal_src=True, flag_reveal_dst=False)
    )
    case.save("tests/golden/siling_flag/")

Under the hood the DSL:
  - Validates every placement: position must match index_to_pos(seat, i).
  - Rejects placements that would violate basic sanity (camp cell, duplicate
    position, off-board, etc.).
  - Emits strictly valid JSON per tests/golden/SCHEMA.md.
  - Fills expected `flag_captured` automatically from the board shape (if dst
    is a stronghold and target piece was JUNQI).

This DSL is used by `tests/golden/scenarios.py` to describe all ~50 core
scenarios in concise Python.  The JSON files are regenerated by running:

    python3 -m tests.golden.scenarios

and committed alongside the DSL code.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

from junqi_core.board import index_to_pos, is_camp, is_on_board
from junqi_core.rules import (
    Event,
    PieceType,
    RULES_VERSION,
    Seat,
    resolve_combat,
    siling_reveals_dst,
    siling_reveals_src,
)

# ===========================================================================
# Re-export convenience aliases so scenario scripts can `from _dsl import *`
# ===========================================================================
# Seat aliases use the new cardinal-direction names (SOUTH / WEST / NORTH /
# EAST). See ADR-111 in docs/DECISIONS.md for why we renamed away from the
# legacy first-person labels (HOME / RIGHT / OPPS / LEFT). Integer values are
# unchanged (SOUTH=0, WEST=1, NORTH=2, EAST=3).

SOUTH: Seat = Seat.SOUTH
WEST: Seat = Seat.WEST
NORTH: Seat = Seat.NORTH
EAST: Seat = Seat.EAST

# Piece aliases
JUNQI = PieceType.JUNQI
DILEI = PieceType.DILEI
ZHADAN = PieceType.ZHADAN
SILING = PieceType.SILING
JUNZH = PieceType.JUNZH
SHIZH = PieceType.SHIZH
LVZH = PieceType.LVZH
TUANZH = PieceType.TUANZH
YINGZH = PieceType.YINGZH
LIANZH = PieceType.LIANZH
PAIZH = PieceType.PAIZH
GONGB = PieceType.GONGB
NONE = PieceType.NONE


# ===========================================================================
# Data classes
# ===========================================================================


@dataclass(slots=True)
class _Piece:
    seat: Seat
    index: int
    piece: PieceType
    pos: tuple[int, int]
    dead: bool = False


@dataclass(slots=True)
class _Action:
    seat: Seat
    src: tuple[int, int]
    dst: tuple[int, int]


@dataclass(slots=True)
class _ExpectedResult:
    event: str | None = None            # auto-filled if None
    flag_reveal_src: bool | None = None
    flag_reveal_dst: bool | None = None
    flag_captured: bool | None = None


@dataclass(slots=True)
class _SeatInfo:
    dead: bool = False
    flag_revealed: bool = False
    jump_count: int = 0


# ===========================================================================
# Case builder
# ===========================================================================


class Case:
    """Fluent builder for a single golden test case."""

    def __init__(self, id_: str, category: str):
        self._id = id_
        self._category = category
        self._description: str = ""
        self._tags: list[str] = []
        self._legacy_divergence: str | None = None
        self._debug_include_private: bool = False
        self._turn: Seat = Seat.SOUTH
        self._move_counter: int = 0
        self._moves_since_last_combat: int = 0
        self._pieces: list[_Piece] = []
        self._info: dict[Seat, _SeatInfo] = {s: _SeatInfo() for s in Seat}
        self._actions: list[_Action] = []
        self._expected_results: list[_ExpectedResult] = []
        self._terminated: bool = False
        self._winner_team: int | None = None
        self._draw: bool = False

    # ---------- metadata ----------

    def describe(self, desc: str) -> "Case":
        self._description = desc
        return self

    def tag(self, *tags: str) -> "Case":
        self._tags.extend(tags)
        return self

    def legacy_divergence(self, reason: str) -> "Case":
        self._legacy_divergence = reason
        return self

    def debug_include_private(self) -> "Case":
        self._debug_include_private = True
        return self

    # ---------- initial state ----------

    def turn(self, seat: Seat) -> "Case":
        self._turn = seat
        return self

    def move_counter(self, n: int) -> "Case":
        self._move_counter = n
        return self

    def moves_since_last_combat(self, n: int) -> "Case":
        self._moves_since_last_combat = n
        return self

    def place(
        self,
        seat: Seat,
        index: int,
        piece: PieceType,
        at: tuple[int, int] | None = None,
        dead: bool = False,
    ) -> "Case":
        """Place a piece owned by `seat` at its home cell (via index) unless
        `at` is given explicitly (used when the piece has already moved)."""
        home_pos = index_to_pos(seat, index)
        pos = at if at is not None else home_pos

        # Validation: `at` must be a sensible on-board cell
        if not is_on_board(*pos):
            raise ValueError(
                f"place({seat.name}, index={index}, piece={piece.name}, at={pos}): "
                f"position is off-board"
            )
        if is_camp(*pos):
            # Pieces can stand ON a camp only if it's empty and entering, not
            # at game-start. Allow but warn.
            pass
        # Duplicate position check
        for existing in self._pieces:
            if existing.pos == pos:
                raise ValueError(
                    f"place({seat.name}, index={index}, piece={piece.name}, at={pos}): "
                    f"position already occupied by {existing.seat.name}:{existing.piece.name}"
                )

        self._pieces.append(_Piece(seat=seat, index=index, piece=piece, pos=pos, dead=dead))
        return self

    def mark_flag_revealed(self, seat: Seat) -> "Case":
        self._info[seat].flag_revealed = True
        return self

    def mark_seat_dead(self, seat: Seat) -> "Case":
        self._info[seat].dead = True
        return self

    # ---------- actions ----------

    def act(
        self,
        seat: Seat,
        src: tuple[int, int],
        dst: tuple[int, int],
    ) -> "Case":
        self._actions.append(_Action(seat=seat, src=src, dst=dst))
        # Append a placeholder expected; `expect_result` fills it.
        self._expected_results.append(_ExpectedResult())
        return self

    def expect_result(
        self,
        *,
        event: str | None = None,
        flag_reveal_src: bool | None = None,
        flag_reveal_dst: bool | None = None,
        flag_captured: bool | None = None,
    ) -> "Case":
        """Set explicit expected fields for the most recent action.
        If any field is None here, auto-fill is attempted at .save() time
        using the rule engine.
        """
        if not self._expected_results:
            raise RuntimeError("call act() before expect_result()")
        er = self._expected_results[-1]
        if event is not None:
            er.event = event
        if flag_reveal_src is not None:
            er.flag_reveal_src = flag_reveal_src
        if flag_reveal_dst is not None:
            er.flag_reveal_dst = flag_reveal_dst
        if flag_captured is not None:
            er.flag_captured = flag_captured
        return self

    def expect_termination(self, *, winner_team: int | None = None, draw: bool = False) -> "Case":
        self._terminated = True
        self._winner_team = winner_team
        self._draw = draw
        return self

    # ---------- autofill + serialize ----------

    def _find_piece_at(self, pos: tuple[int, int]) -> _Piece | None:
        for p in self._pieces:
            if not p.dead and p.pos == pos:
                return p
        return None

    def _autofill(self) -> None:
        """For any action with unset expected fields, compute them from rules.

        Note: this is a single-action lookahead; it does NOT simulate the full
        multi-action sequence. For scenarios with N > 1 actions, the author
        must fill expectations manually (or we delegate to oracle_runner).
        """
        for i, (action, er) in enumerate(zip(self._actions, self._expected_results)):
            # Only autofill for single-action cases to keep logic simple;
            # otherwise trust the author.
            if len(self._actions) > 1:
                continue

            src_piece = self._find_piece_at(action.src)
            dst_piece = self._find_piece_at(action.dst)

            if src_piece is None:
                raise ValueError(
                    f"action {i}: no piece at src={action.src}"
                )

            if dst_piece is None:
                # Plain move
                if er.event is None:
                    er.event = "MOVE"
                if er.flag_reveal_src is None:
                    er.flag_reveal_src = False
                if er.flag_reveal_dst is None:
                    er.flag_reveal_dst = False
                if er.flag_captured is None:
                    er.flag_captured = False
            else:
                # Combat
                event = resolve_combat(src_piece.piece, dst_piece.piece)
                if er.event is None:
                    er.event = event.name
                if er.flag_reveal_src is None:
                    er.flag_reveal_src = siling_reveals_src(
                        src_piece.piece, dst_piece.piece, event
                    )
                if er.flag_reveal_dst is None:
                    er.flag_reveal_dst = siling_reveals_dst(
                        src_piece.piece, dst_piece.piece, event
                    )
                if er.flag_captured is None:
                    er.flag_captured = dst_piece.piece is PieceType.JUNQI

    def to_dict(self) -> dict[str, Any]:
        self._autofill()

        pieces_json = [
            {
                "seat": p.seat.value,
                "index": p.index,
                "type": p.piece.name,
                "pos": list(p.pos),
                "dead": p.dead,
            }
            for p in self._pieces
        ]
        info_json = [
            {
                "seat": s.value,
                "dead": self._info[s].dead,
                "flag_revealed": self._info[s].flag_revealed,
                "jump_count": self._info[s].jump_count,
            }
            for s in Seat
        ]
        actions_json = [
            {"seat": a.seat.value, "src": list(a.src), "dst": list(a.dst)}
            for a in self._actions
        ]
        results_json = [
            {
                "src": list(a.src),
                "dst": list(a.dst),
                "event": er.event,
                "flag_reveal_src": er.flag_reveal_src,
                "flag_reveal_dst": er.flag_reveal_dst,
                "flag_captured": er.flag_captured,
            }
            for a, er in zip(self._actions, self._expected_results)
        ]

        doc: dict[str, Any] = {
            "schema_version": "1.0",
            "rules_version": RULES_VERSION,
            "category": self._category,
            "id": self._id,
            "description": self._description,
            "tags": self._tags,
            "legacy_divergence": self._legacy_divergence,
            "debug_include_private": self._debug_include_private,
            "pre_state": {
                "turn": self._turn.value,
                "move_counter": self._move_counter,
                "moves_since_last_combat": self._moves_since_last_combat,
                "pieces": pieces_json,
                "info": info_json,
            },
            "actions": actions_json,
            "expected": {
                "results": results_json,
                "terminated": self._terminated,
                "winner_team": self._winner_team,
                "draw": self._draw,
            },
        }
        return doc

    def save(self, out_dir: str | Path) -> Path:
        """Write the JSON to `out_dir/{id}.json` and return the path."""
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{self._id}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)
            f.write("\n")
        return path


# ===========================================================================
# Setup-validation case (different schema: no pre_state, has setup_only)
# ===========================================================================


class SetupCase:
    """Builder for setup_validation golden cases (§1.3 C1-C5 tests)."""

    def __init__(self, id_: str):
        self._id = id_
        self._category = "setup_validation"
        self._description: str = ""
        self._tags: list[str] = []
        self._legacy_divergence: str | None = (
            "Legacy engine does not validate setups; this is a new junqi_core constraint."
        )
        self._lineups: list[list[str]] = []
        self._expect_valid: bool = True
        self._expect_violations: list[str] = []

    def describe(self, desc: str) -> "SetupCase":
        self._description = desc
        return self

    def tag(self, *tags: str) -> "SetupCase":
        self._tags.extend(tags)
        return self

    def with_lineups(self, lineups: Sequence[Sequence[PieceType | str]]) -> "SetupCase":
        """Set all 4 seats' lineups."""
        assert len(lineups) == 4, "need 4 seats"
        self._lineups = [
            [(p.name if isinstance(p, PieceType) else p) for p in lu] for lu in lineups
        ]
        return self

    def expect_valid(self, *, valid: bool, violations: Sequence[str] = ()) -> "SetupCase":
        self._expect_valid = valid
        self._expect_violations = list(violations)
        return self

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "1.0",
            "rules_version": RULES_VERSION,
            "category": self._category,
            "id": self._id,
            "description": self._description,
            "tags": self._tags,
            "legacy_divergence": self._legacy_divergence,
            "debug_include_private": False,
            "setup_only": {
                "lineups": self._lineups,
                "expect_valid": self._expect_valid,
                "expect_violations": self._expect_violations,
            },
        }

    def save(self, out_dir: str | Path) -> Path:
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{self._id}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)
            f.write("\n")
        return path
