"""Golden test scenario catalog.

Run this module to regenerate all JSON files under `tests/golden/<category>/`:

    PYTHONPATH=. python3 -m tests.golden.scenarios

Each scenario function registers one or more golden cases and saves them.
The catalog is organized by RULES.md section / DECISIONS.md ADR number so
reviewers can check coverage at a glance.

Coverage goals for Phase 0.1 (hand-written core set):
  - move_gen/           : 12 scenarios  (§2.3 moves)
  - battle/             : 10 scenarios  (§3.1 combat table)
  - siling_flag/        :  7 scenarios  (§3.2 Q7)
  - stronghold/         :  6 scenarios  (§2.6 + ADR-006)
  - inference/          :  8 scenarios  (§3.4 special deductions)
  - setup_validation/   :  8 scenarios  (§1.3 C1-C5)
  - full_game/          :  3 scenarios  (integration)

Remaining bulk cases (additional full-game traces, exhaustive piece-vs-piece
matrix, etc.) are generated by `tools/oracle_runner.py` in a later Phase-0.1
task using the legacy engine as ground truth.
"""

from __future__ import annotations

from pathlib import Path

from ._dsl import (
    # seats
    SOUTH, NORTH, EAST, WEST,
    # pieces
    JUNQI, DILEI, ZHADAN,
    SILING, JUNZH, SHIZH, LVZH, TUANZH,
    YINGZH, LIANZH, PAIZH, GONGB, NONE,
    # builders
    Case, SetupCase,
)
from junqi_core.board import index_to_pos
from junqi_core.rules import (
    CAMP_INDICES, STRONGHOLD_INDICES,
    PIECE_COUNTS, PieceType,
    SLOTS_PER_SEAT,
)


GOLDEN_ROOT = Path(__file__).parent


# ===========================================================================
# HELPERS to build a legal 30-slot lineup for setup_validation tests
# ===========================================================================


def _canonical_valid_lineup() -> list[str]:
    """Produce one deterministic, rule-compliant lineup (used as a template).

    The exact placement below was chosen to be easy to mutate in C1..C5 tests.
    Camps (indices 6, 8, 12, 16, 18) are NONE.
    Flag at index 26 (stronghold). Mines at 20, 22, 24. Bombs at 5, 7.
    """
    lu: list[str | None] = [None] * SLOTS_PER_SEAT
    # Camps
    for i in (6, 8, 12, 16, 18):
        lu[i] = "NONE"
    # Flag
    lu[26] = "JUNQI"
    # Mines (all 3, all in back two rows)
    lu[20] = "DILEI"
    lu[22] = "DILEI"
    lu[24] = "DILEI"
    # Other stronghold (28) gets a non-flag piece
    lu[28] = "GONGB"
    # Bombs (not in row 0)
    lu[5] = "ZHADAN"
    lu[7] = "ZHADAN"
    # Ranked combatants
    lu[0] = "SILING"
    lu[1] = "JUNZH"
    lu[2] = "SHIZH"
    lu[3] = "SHIZH"
    lu[4] = "LVZH"
    lu[9] = "LVZH"
    lu[10] = "TUANZH"
    lu[11] = "TUANZH"
    lu[13] = "YINGZH"
    lu[14] = "YINGZH"
    lu[15] = "LIANZH"
    lu[17] = "LIANZH"
    lu[19] = "LIANZH"
    lu[21] = "PAIZH"
    lu[23] = "PAIZH"
    lu[25] = "PAIZH"
    lu[27] = "GONGB"
    lu[29] = "GONGB"
    assert all(x is not None for x in lu)
    return [x for x in lu]  # type: ignore[misc]


def _canonical_setup() -> list[list[str]]:
    return [_canonical_valid_lineup() for _ in range(4)]


# ===========================================================================
# HELPERS for combat scenarios
# ===========================================================================


def _place_fillers(
    case: "Case",
    *,
    skip: tuple[tuple[int, int], ...] = (),
    skip_seats: tuple = (),
) -> "Case":
    """Place one surviving PAIZH on each of the four seats' home rows.

    This ensures _check_victory() does not mis-fire due to a seat having no
    live pieces left. Cells listed in `skip` (already occupied by an attacker
    / defender / other scenario piece) are not filled. Seats listed in
    `skip_seats` are skipped entirely (e.g. when the scenario places its own
    WEST defender at WEST's idx=0 cell, we still add a WEST filler at a
    different index below, so that code path is not needed in practice).
    """
    # Default fillers (all on rail / home rows, none conflicting with the
    # standard attack templates (6,10)->(5,10) / (1,9)->(0,9) / (10,10)->(11,10)).
    fillers = [
        (SOUTH,  0, PAIZH, (10, 11)),   # SOUTH idx=0
        (NORTH,  0, PAIZH, (6, 5)),     # NORTH idx=0
        (WEST, 5, PAIZH, (4, 10)),    # WEST idx=5
        (EAST,  0, PAIZH, (11, 6)),    # EAST idx=0
    ]
    for seat, idx, piece, pos in fillers:
        if seat in skip_seats:
            continue
        if pos in skip:
            continue
        case.place(seat, index=idx, piece=piece, at=pos)
    return case


# ===========================================================================
# §2 move_gen: basic movement scenarios
# ===========================================================================


def gen_move_gen() -> None:
    out = GOLDEN_ROOT / "move_gen"

    c = Case("adj_orthogonal_one_step", "move_gen") \
        .describe("SOUTH PAIZH moves one cell forward on non-rail. Basic adj move.") \
        .tag("adj", "basic") \
        .turn(SOUTH) \
        .place(SOUTH, index=2, piece=PAIZH)
    _place_fillers(c, skip=(index_to_pos(SOUTH, 2),))
    c.act(SOUTH, src=(8, 11), dst=(8, 10)).save(out)

    c = Case("adj_diagonal_into_camp", "move_gen") \
        .describe("SOUTH LIANZH at (10,13) moves diagonally into camp (9,12). Legal per §2.3.1.") \
        .tag("adj", "camp", "diagonal") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=LIANZH)
    _place_fillers(c, skip=(index_to_pos(SOUTH, 10),))
    c.act(SOUTH, src=(10, 13), dst=(9, 12)).save(out)

    c = Case("adj_diagonal_out_of_camp", "move_gen") \
        .describe("SOUTH PAIZH sitting in camp (8,13) moves diagonally out to (7,12), which is also a camp. Legal: src is camp.") \
        .tag("adj", "camp", "diagonal") \
        .turn(SOUTH) \
        .place(SOUTH, index=12, piece=PAIZH, at=(8, 13))
    _place_fillers(c, skip=((8, 13),))
    c.act(SOUTH, src=(8, 13), dst=(7, 12)).save(out)

    c = Case("adj_along_rail_one_step", "move_gen") \
        .describe("SOUTH LIANZH at rail cell (10,11) moves 1 step to rail (10,12). Basic adj move.") \
        .tag("adj", "rail") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=LIANZH)
    _place_fillers(c, skip=((10, 11),), skip_seats=(SOUTH,))
    c.act(SOUTH, src=(10, 11), dst=(10, 12)).save(out)

    c = Case("rail_straight_horizontal_long", "move_gen") \
        .describe("SOUTH LIANZH rides along front-row rail from (10,11) to (6,11).") \
        .tag("rail", "straight") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=LIANZH)
    _place_fillers(c, skip=((10, 11),), skip_seats=(SOUTH,))
    c.act(SOUTH, src=(10, 11), dst=(6, 11)).save(out)

    c = Case("gongb_rail_bfs_corner_to_corner", "move_gen") \
        .describe("SOUTH GONGB uses rail BFS to go (10,11) → (6,11), same as non-engineer here.") \
        .tag("rail", "gongb") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=GONGB)
    _place_fillers(c, skip=((10, 11),), skip_seats=(SOUTH,))
    c.act(SOUTH, src=(10, 11), dst=(6, 11)).save(out)

    c = Case("gongb_rail_turn_at_corner", "move_gen") \
        .describe("SOUTH GONGB turns at rail corner: (6,11) → (10,15) requires a corner turn.") \
        .tag("rail", "gongb", "corner-turn") \
        .turn(SOUTH) \
        .place(SOUTH, index=4, piece=GONGB)
    _place_fillers(c, skip=((6, 11),))
    c.act(SOUTH, src=(6, 11), dst=(10, 15)).save(out)


# ===========================================================================
# §3.1 battle: combat table coverage
# ===========================================================================
#
# Template:
#   SOUTH attacker at (6,10) (nine-grid cell, orthogonally adjacent to WEST
#   front-row rail cell (5,10)).  WEST (not NORTH!) is SOUTH's ENEMY (blue
#   team); NORTH is SOUTH's teammate.  A filler is placed for every surviving
#   seat so that _check_victory() does not spuriously terminate the game.
#   For stronghold scenarios, SOUTH attacker is pre-advanced to (1,9)
#   attacking (0,9) (WEST's stronghold at WEST idx=26).


def gen_battle() -> None:
    out = GOLDEN_ROOT / "battle"

    c = Case("siling_eats_junzh", "battle") \
        .describe("SOUTH SILING eats WEST JUNZH. EAT event. No flag reveal.") \
        .tag("ranked", "eat") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=0, piece=JUNZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("same_rank_bomb_junzh", "battle") \
        .describe("SOUTH JUNZH vs WEST JUNZH. Same-rank mutual death; neither is SILING → no flag reveal.") \
        .tag("bomb", "same-rank") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=JUNZH, at=(6, 10)) \
        .place(WEST, index=0, piece=JUNZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("zhadan_vs_zhadan", "battle") \
        .describe("SOUTH ZHADAN vs WEST ZHADAN. BOMB, no reveal.") \
        .tag("bomb", "zhadan") \
        .turn(SOUTH) \
        .place(SOUTH, index=5, piece=ZHADAN, at=(6, 10)) \
        .place(WEST, index=0, piece=ZHADAN, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("paizh_hits_dilei_killed", "battle") \
        .describe("SOUTH PAIZH vs WEST DILEI. KILLED, mine stays, no reveal.") \
        .tag("dilei", "killed") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(6, 10)) \
        .place(WEST, index=25, piece=DILEI, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("gongb_eats_dilei", "battle") \
        .describe("SOUTH GONGB eats WEST DILEI. Engineer-only move; no reveal.") \
        .tag("gongb", "dilei", "engineer-signature") \
        .turn(SOUTH) \
        .place(SOUTH, index=14, piece=GONGB, at=(6, 10)) \
        .place(WEST, index=25, piece=DILEI, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("piece_eats_junqi_flag_captured", "battle") \
        .describe("SOUTH LIANZH eats WEST JUNQI. EAT with flag_captured=True triggers WEST surrender (EAST is still alive → blue team alive → not terminated).") \
        .tag("eat", "flag-captured") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=LIANZH, at=(1, 9)) \
        .place(WEST, index=26, piece=JUNQI, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("shizh_eats_lvzh", "battle") \
        .describe("SOUTH SHIZH eats WEST LVZH. Plain ranked EAT.") \
        .tag("ranked", "eat") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SHIZH, at=(6, 10)) \
        .place(WEST, index=0, piece=LVZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("paizh_attacks_shizh_killed", "battle") \
        .describe("SOUTH PAIZH vs WEST SHIZH. Attacker weaker → KILLED.") \
        .tag("ranked", "killed") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(6, 10)) \
        .place(WEST, index=0, piece=SHIZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("paizh_eats_gongb", "battle") \
        .describe("SOUTH PAIZH eats WEST GONGB. PAIZH is only stronger than GONGB among ranked; strong inference cue.") \
        .tag("ranked", "eat", "inference-cue") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(6, 10)) \
        .place(WEST, index=14, piece=GONGB, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("plain_move_empty_dst", "battle") \
        .describe("SOUTH PAIZH moves to empty cell; MOVE event.") \
        .tag("move") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=PAIZH)
    _place_fillers(c, skip=((10, 11),), skip_seats=(SOUTH,))
    c.act(SOUTH, src=(10, 11), dst=(10, 12)).save(out)


# ===========================================================================
# §3.2 siling_flag: Q7 SILING flag-reveal scenarios
# ===========================================================================


def gen_siling_flag() -> None:
    out = GOLDEN_ROOT / "siling_flag"

    c = Case("siling_eats_junzh_no_reveal", "siling_flag") \
        .describe("SOUTH SILING eats WEST JUNZH. Attacker survived → no reveal.") \
        .tag("Q7", "siling", "no-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=0, piece=JUNZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("siling_vs_siling_both_reveal", "siling_flag") \
        .describe("Two SILINGs collide; same-rank BOMB; both reveal (Q7).") \
        .tag("Q7", "siling", "double-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=0, piece=SILING, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("siling_attacks_zhadan_src_only_reveal", "siling_flag") \
        .describe("SOUTH SILING attacks WEST ZHADAN. BOMB; only src reveal. Key Q7 deduction cue.") \
        .tag("Q7", "siling", "zhadan", "deduction-cue") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=11, piece=ZHADAN, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("zhadan_attacks_siling_dst_only_reveal", "siling_flag") \
        .describe("SOUTH ZHADAN vs WEST SILING. BOMB; only dst reveals.") \
        .tag("Q7", "siling", "zhadan", "mirror") \
        .turn(SOUTH) \
        .place(SOUTH, index=8, piece=ZHADAN, at=(6, 10)) \
        .place(WEST, index=0, piece=SILING, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("siling_hits_landmine_src_reveal", "siling_flag") \
        .describe("SOUTH SILING hits WEST DILEI. KILLED (src dies). src reveals.") \
        .tag("Q7", "siling", "dilei", "killed") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=25, piece=DILEI, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("junzh_attacks_siling_dst_reveal_junzh_survives", "siling_flag") \
        .describe("SOUTH JUNZH attacks WEST SILING. SILING (rank 5) is stronger than JUNZH (rank 6) → KILLED; src JUNZH dies, dst SILING survives. Neither's SILING actually dies → no flag reveal (per Q7 wording: reveal fires on SILING DEATH, not involvement).") \
        .tag("Q7", "siling", "killed", "no-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=JUNZH, at=(6, 10)) \
        .place(WEST, index=0, piece=SILING, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("siling_eats_pai_no_reveal", "siling_flag") \
        .describe("SOUTH SILING eats WEST PAIZH. Attacker (SILING) survived, defender was not SILING → no reveal.") \
        .tag("Q7", "siling", "eat", "no-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=25, piece=PAIZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)


# ===========================================================================
# §2.6 + ADR-006 stronghold: probing strategy scenarios
# ===========================================================================


def gen_stronghold() -> None:
    out = GOLDEN_ROOT / "stronghold"

    # WEST strongholds are at WEST indices 26, 28 → world (0, 9) and (0, 7).
    # SOUTH attacker is pre-positioned at (1, 9) (WEST idx=21, non-stronghold,
    # orthogonally adjacent to (0, 9)).

    c = Case("paizh_probes_flag_stronghold_eat", "stronghold") \
        .describe("SOUTH PAIZH advanced to (1,9) attacks WEST stronghold (0,9) containing the flag. EAT + flag_captured=True. WEST surrenders; EAST still alive → not terminated.") \
        .tag("stronghold", "probe", "flag-captured") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(1, 9)) \
        .place(WEST, index=26, piece=JUNQI, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("paizh_probes_stronghold_hits_dilei", "stronghold") \
        .describe("SOUTH PAIZH probes WEST stronghold (0,9) containing a DILEI. KILLED; attacker dies, mine stays; the flag must be in the OTHER stronghold at (0,7).") \
        .tag("stronghold", "probe", "dilei", "three-mine-hint") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(1, 9)) \
        .place(WEST, index=26, piece=DILEI, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("paizh_probes_stronghold_hits_lianzh_eat", "stronghold") \
        .describe("SOUTH PAIZH probes WEST stronghold (0,9) containing a LIANZH. LIANZH(11) < PAIZH(12); lower number is stronger → PAIZH KILLED.") \
        .tag("stronghold", "probe", "killed") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(1, 9)) \
        .place(WEST, index=26, piece=LIANZH, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("shizh_probes_stronghold_eats_lianzh", "stronghold") \
        .describe("SOUTH SHIZH attacks WEST stronghold (0,9) containing LIANZH. SHIZH(7) stronger → EAT. The flag must now be in the OTHER stronghold (0,7).") \
        .tag("stronghold", "probe", "eat", "flag-other-stronghold") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SHIZH, at=(1, 9)) \
        .place(WEST, index=26, piece=LIANZH, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("gongb_eats_stronghold_dilei", "stronghold") \
        .describe("SOUTH GONGB eats DILEI at WEST stronghold (0,9). EAT. The flag must be in the OTHER stronghold.") \
        .tag("stronghold", "gongb", "dilei") \
        .turn(SOUTH) \
        .place(SOUTH, index=14, piece=GONGB, at=(1, 9)) \
        .place(WEST, index=26, piece=DILEI, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("zhadan_attacks_stronghold_zhadan_bomb", "stronghold") \
        .describe("SOUTH ZHADAN attacks WEST stronghold (0,9) containing ZHADAN. BOMB double-death.") \
        .tag("stronghold", "bomb") \
        .turn(SOUTH) \
        .place(SOUTH, index=5, piece=ZHADAN, at=(1, 9)) \
        .place(WEST, index=26, piece=ZHADAN, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)


# ===========================================================================
# §3.4 inference: special deduction scenarios
# ===========================================================================


def gen_inference() -> None:
    out = GOLDEN_ROOT / "inference"

    c = Case("infer_paizh_eats_gongb", "inference") \
        .describe("From BOMB/EAT + ranks: SOUTH PAIZH eats WEST piece. Since PAIZH(12) only beats GONGB(13), observers deduce dst was GONGB.") \
        .tag("Q2", "inference", "ranked-deduction") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=PAIZH, at=(6, 10)) \
        .place(WEST, index=14, piece=GONGB, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_gongb_eats_dilei", "inference") \
        .describe("GONGB is the only piece that can EAT a DILEI. If observers see EAT where dst was immobile in back rank → src=GONGB dst=DILEI.") \
        .tag("Q2", "inference", "engineer-signature") \
        .turn(SOUTH) \
        .place(SOUTH, index=14, piece=GONGB, at=(6, 10)) \
        .place(WEST, index=25, piece=DILEI, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_siling_on_mine_flag_revealed", "inference") \
        .describe("KILLED event where src's flag reveals → src was SILING. If dst was immobile in back rank → dst was DILEI.") \
        .tag("Q2", "Q7", "inference", "siling-on-mine") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=25, piece=DILEI, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_bomb_src_reveal_means_siling_vs_zhadan", "inference") \
        .describe("BOMB + only-src-reveal uniquely implies src=SILING and dst=ZHADAN. The Q7 teaching example.") \
        .tag("Q2", "Q7", "inference", "bomb-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=11, piece=ZHADAN, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_bomb_both_reveal_means_double_siling", "inference") \
        .describe("BOMB + both-reveal uniquely implies both pieces were SILING. Very expensive trade.") \
        .tag("Q2", "Q7", "inference", "double-siling") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SILING, at=(6, 10)) \
        .place(WEST, index=0, piece=SILING, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_bomb_no_reveal_same_rank", "inference") \
        .describe("BOMB + no-reveal means neither was SILING. Could be same-rank ranked pieces OR bomb involvement.") \
        .tag("Q2", "inference", "bomb-no-reveal") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=JUNZH, at=(6, 10)) \
        .place(WEST, index=0, piece=JUNZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)

    c = Case("infer_stronghold_other_is_flag", "inference") \
        .describe("After EAT/BOMB/KILLED at one stronghold where flag_captured=False, observers deduce the OTHER stronghold must contain the flag.") \
        .tag("Q2", "inference", "flag-location") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SHIZH, at=(1, 9)) \
        .place(WEST, index=26, piece=LIANZH, at=(0, 9))
    _place_fillers(c, skip=((1, 9), (0, 9)))
    c.act(SOUTH, src=(1, 9), dst=(0, 9)).save(out)

    c = Case("infer_shizh_eats_unknown_means_dst_weaker", "inference") \
        .describe("SOUTH SHIZH (publicly known) EATs unknown WEST piece. Observers deduce dst rank strictly weaker than SHIZH(7), i.e. dst ∈ {LVZH..GONGB}.") \
        .tag("Q2", "inference", "rank-lower-bound") \
        .turn(SOUTH) \
        .place(SOUTH, index=3, piece=SHIZH, at=(6, 10)) \
        .place(WEST, index=14, piece=LIANZH, at=(5, 10))
    _place_fillers(c, skip=((6, 10), (5, 10)))
    c.act(SOUTH, src=(6, 10), dst=(5, 10)).save(out)


# ===========================================================================
# §1.3 setup_validation: C1-C5 hard-constraint tests
# ===========================================================================


def gen_setup_validation() -> None:
    out = GOLDEN_ROOT / "setup_validation"

    # 1. All-valid: the canonical setup
    SetupCase("valid_canonical_setup") \
        .describe("The canonical valid setup for all 4 seats passes all C1-C5.") \
        .tag("C1", "C2", "C3", "C4", "C5", "valid") \
        .with_lineups(_canonical_setup()) \
        .expect_valid(valid=True, violations=()) \
        .save(out)

    # 2. C1: piece at camp index 6
    bad1 = _canonical_valid_lineup()
    bad1[6] = "PAIZH"
    bad1[0] = "NONE"  # compensate counts
    SetupCase("c1_piece_in_camp_6") \
        .describe("C1 violation: piece placed at camp index 6 (and index 0 emptied to balance).") \
        .tag("C1", "invalid") \
        .with_lineups([bad1] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C1",)) \
        .save(out)

    # 3. C2: flag NOT in stronghold
    bad2 = _canonical_valid_lineup()
    # swap flag from 26 to 25 (non-stronghold)
    bad2[25], bad2[26] = bad2[26], bad2[25]
    SetupCase("c2_flag_not_in_stronghold") \
        .describe("C2 violation: JUNQI placed at index 25 (non-stronghold), and the original slot gets the swapped piece.") \
        .tag("C2", "invalid") \
        .with_lineups([bad2] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C2",)) \
        .save(out)

    # 4. C3: DILEI in front row
    bad3 = _canonical_valid_lineup()
    # swap a DILEI (at 20) with index 0
    bad3[0], bad3[20] = bad3[20], bad3[0]
    SetupCase("c3_dilei_in_front_row") \
        .describe("C3 violation: DILEI placed at index 0 (front row) via swap with a ranked piece.") \
        .tag("C3", "invalid") \
        .with_lineups([bad3] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C3",)) \
        .save(out)

    # 5. C4: ZHADAN in front row
    bad4 = _canonical_valid_lineup()
    # ZHADAN is at 5; swap with index 0
    bad4[0], bad4[5] = bad4[5], bad4[0]
    SetupCase("c4_zhadan_in_front_row") \
        .describe("C4 violation: ZHADAN placed at index 0 (front row) via swap.") \
        .tag("C4", "invalid") \
        .with_lineups([bad4] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C4",)) \
        .save(out)

    # 6. C5: extra SILING (count=2, expected=1)
    bad5 = _canonical_valid_lineup()
    # find a GONGB (should exist) and replace with SILING
    gongb_idx = next(i for i, v in enumerate(bad5) if v == "GONGB")
    bad5[gongb_idx] = "SILING"
    SetupCase("c5_extra_siling") \
        .describe("C5 violation: SILING count = 2 (GONGB replaced with SILING). Missing 1 GONGB and excess 1 SILING.") \
        .tag("C5", "invalid") \
        .with_lineups([bad5] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C5",)) \
        .save(out)

    # 7. Combined C1 + C3
    bad6 = _canonical_valid_lineup()
    bad6[6] = "PAIZH"       # C1
    bad6[0] = "DILEI"       # C3 + extra logic
    # original [0]="SILING" — now SILING is missing (C5 also triggered);
    # original [6]="NONE" — still 5 NONE's if we kept [0] as something else.
    # Actually by making [0]=DILEI, we've introduced: +1 DILEI, -1 SILING,
    # +1 PAIZH (at 6), -1 NONE. Counts now: DILEI=4 (was 3), SILING=0, PAIZH=4.
    # So we get C1 + C3 + C5 all. Accept that; test expect_violations accordingly.
    SetupCase("combined_c1_c3_c5") \
        .describe("Multiple-violation case: piece at camp + DILEI in front + count imbalance.") \
        .tag("C1", "C3", "C5", "invalid", "combined") \
        .with_lineups([bad6] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("C1", "C3", "C5")) \
        .save(out)

    # 8. Wrong length (LENGTH violation)
    short = _canonical_valid_lineup()[:-1]  # 29 slots
    SetupCase("length_mismatch") \
        .describe("Lineup with only 29 slots (short by 1). Rejected before C1-C5 checks.") \
        .tag("LENGTH", "invalid") \
        .with_lineups([short] + [_canonical_valid_lineup()] * 3) \
        .expect_valid(valid=False, violations=("LENGTH",)) \
        .save(out)


# ===========================================================================
# full_game: integration scenarios (author manually fills expected; oracle
# will cross-verify in a later step).
# ===========================================================================


def gen_full_game() -> None:
    out = GOLDEN_ROOT / "full_game"

    # Scenario 1: rapid flag capture ending the game.  SOUTH captures WEST's
    # flag; WEST surrenders.  EAST has no live pieces in this minimal setup
    # (no EAST filler), so the blue team is dead → red team wins.
    Case("rapid_flag_capture", "full_game") \
        .describe("Minimal scenario: SOUTH SILING captures WEST's flag at stronghold (0,9). WEST surrenders; EAST has no live pieces either → blue team dead → red team wins.") \
        .tag("full-game", "flag-capture", "winner=0") \
        .turn(SOUTH) \
        .place(SOUTH, index=10, piece=SILING, at=(1, 9)) \
        .place(WEST, index=26, piece=JUNQI, at=(0, 9)) \
        .act(SOUTH, src=(1, 9), dst=(0, 9)) \
        .expect_result(event="EAT", flag_reveal_src=False, flag_reveal_dst=False, flag_captured=True) \
        .expect_termination(winner_team=0, draw=False) \
        .save(out)

    # Scenario 2: placeholder for 200-move draw (to be filled by oracle)
    Case("draw_200_moves_no_combat", "full_game") \
        .describe("Placeholder: both teams shuffle pieces without combat for 200 moves; draw declared. Expected sequence will be filled by oracle_runner with a crafted trajectory.") \
        .tag("full-game", "draw", "placeholder") \
        .legacy_divergence("Draw rule is new; legacy engine never declares a draw.") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=PAIZH) \
        .save(out)

    # Scenario 3: team death by flag capture + no-legal-moves combined
    Case("team_death_flag_then_no_moves", "full_game") \
        .describe("Placeholder: SOUTH's flag captured first, then NORTH teammate later has no legal moves. Red team (SOUTH+NORTH) partial death case.") \
        .tag("full-game", "team-death", "placeholder") \
        .turn(SOUTH) \
        .place(SOUTH, index=0, piece=PAIZH) \
        .save(out)


# ===========================================================================
# main entry point
# ===========================================================================


def main() -> None:
    gen_move_gen()
    gen_battle()
    gen_siling_flag()
    gen_stronghold()
    gen_inference()
    gen_setup_validation()
    gen_full_game()
    print("All Phase 0.1 core scenarios generated.")


if __name__ == "__main__":
    main()
